export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const VIDEOGAME_NAME = "VIDEOGAME_NAME";
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const FILTER_VIDEOGAME = "FILTER_VIDEOGAME";
export const ORDER_VIDEOGAME = "ORDER_VIDEOGAME";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
